import test from 'node:test';import assert from 'node:assert/strict';import {createHash} from 'node:crypto';
import {database} from './helpers/d1.mjs';import {login,hashPin,digest,session,verifyPin} from '../worker/auth.ts';
const legacy=pin=>'sha256$synthetic-only$'+createHash('sha256').update('synthetic-only|'+pin).digest('base64');
async function setup(hash=legacy('0042')){const db=await database();db.sqlite.exec("INSERT INTO classes VALUES('c','가상반');INSERT INTO accounts(id,legacy_identity,display_name,class_id,role) VALUES('a','synthetic:a','가상로그인','c','student')");db.sqlite.prepare('INSERT INTO credentials VALUES(?,?,?)').run('a','가상로그인',hash);return db;}
test('legacy login upgrades PIN once, validates live account and retains zero-prefixed PIN',async()=>{const db=await setup(),stages=[];try{const r=await login({DB:db.DB},' 가상로그인 ',' 0042 ',true,s=>stages.push(s));assert.equal(r.id,'a');assert.equal((await session({DB:db.DB},r.token)).class_id,'c');const hash=db.sqlite.prepare('SELECT pin_hash FROM credentials').get().pin_hash;assert.match(hash,/^pbkdf2\$600000\$/);assert(await verifyPin('0042',hash));assert.equal(await verifyPin('42',hash),false);assert.equal(stages.filter(s=>s==='pin_upgrade_begin').length,1);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM login_attempts').get().n,0);const expires=db.sqlite.prepare('SELECT expires_at FROM sessions').get().expires_at;assert(expires>Date.now()+29*86400000);}finally{db.close();}});
test('PBKDF2 login leaves verified credential unchanged and uses one KDF',async()=>{const hash=await hashPin('0042'),db=await setup(hash),stages=[];try{db.sqlite.exec("CREATE TABLE credential_updates(n INTEGER);INSERT INTO credential_updates VALUES(0);CREATE TRIGGER count_update AFTER UPDATE ON credentials BEGIN UPDATE credential_updates SET n=n+1;END;");const r=await login({DB:db.DB},'가상로그인','0042',false,s=>stages.push(s));assert(r.token);assert.equal(db.sqlite.prepare('SELECT n FROM credential_updates').get().n,0);assert.equal(stages.filter(s=>s==='pin_verify_begin').length,1);assert.equal(stages.includes('pin_upgrade_begin'),false);assert.equal(db.sqlite.prepare('SELECT pin_hash FROM credentials').get().pin_hash,hash);}finally{db.close();}});
for(const [pin,accepted] of [['0042',true],['0043',false]])test('credential changes during legacy upgrade are reverified: '+(accepted?'same PIN succeeds':'changed PIN fails closed'),async()=>{const current=await hashPin(pin),db=await setup(),stages=[];let batches=0;const DB={...db.DB,batch:async statements=>{if(++batches===2)db.sqlite.prepare('UPDATE credentials SET pin_hash=?').run(current);return db.DB.batch(statements);}};try{const request=login({DB},'가상로그인','0042',false,s=>stages.push(s));if(accepted){assert((await request).token);assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,1);}else{await assert.rejects(request,e=>e.code==='E_AUTH');assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(db.sqlite.prepare('SELECT attempts FROM login_attempts').get().attempts,1);}assert(stages.includes('conflict_verify_begin'));assert.equal(db.sqlite.prepare('SELECT pin_hash FROM credentials').get().pin_hash,current);}finally{db.close();}});
test('inactive account cannot obtain session or reset attempts, and same hash is not rederived',async()=>{const db=await setup(await hashPin('0042')),stages=[];let batches=0;const DB={...db.DB,batch:async statements=>{if(++batches===2)db.sqlite.exec('UPDATE accounts SET active=0');return db.DB.batch(statements);}};try{await assert.rejects(login({DB},'가상로그인','0042',false,s=>stages.push(s)),e=>e.code==='E_AUTH');assert.equal(db.sqlite.prepare('SELECT COUNT(*) AS n FROM sessions').get().n,0);assert.equal(db.sqlite.prepare('SELECT attempts FROM login_attempts').get().attempts,1);assert.equal(stages.includes('conflict_verify_begin'),false);}finally{db.close();}});
test('rate limit blocks ninth attempt before KDF and expires after fifteen minutes',async()=>{const db=await setup();try{for(let i=0;i<8;i++)await assert.rejects(login({DB:db.DB},'가상로그인','wrong',false),e=>e.code==='E_AUTH');const stages=[];await assert.rejects(login({DB:db.DB},'가상로그인','0042',false,s=>stages.push(s)),e=>e.code==='E_RATE');assert.equal(stages.includes('pin_verify_begin'),false);db.sqlite.prepare('UPDATE login_attempts SET window_start=? WHERE key=?').run(Date.now()-900001,await digest('가상로그인'));assert((await login({DB:db.DB},'가상로그인','0042',false)).token);}finally{db.close();}});
