import test from 'node:test';import assert from 'node:assert/strict';import {readFile} from 'node:fs/promises';import vm from 'node:vm';import {execFileSync} from 'node:child_process';
const candidate=await readFile('index.html','utf8'),baseline=execFileSync('git',['show','origin/main:index.html'],{encoding:'utf8'});
function harness(html){const calls=[],list={innerHTML:'',replaceChildren(){this.innerHTML='';}},more={disabled:false,textContent:''};const c=vm.createContext({window:{},currentUser:{name:'가상교사',role:'선생님'},_getToken:()=>c.token,token:'fake',FEED_PAGE_SIZE:12,_feedLimit:12,_feedOffset:0,_feedHasMore:false,_feedLoading:false,_feedRefreshPending:false,_feedRequestGeneration:0,feedEntries:[],document:{getElementById:id=>id==='feed-list'?list:more},renderFeed:()=>{list.innerHTML=c.feedEntries.map(e=>e.id).join(',');},renderFeedAppend:()=>{list.innerHTML=c.feedEntries.map(e=>e.id).join(',');},tryDeepLinkAfterRender:()=>{},console:{error(){}},google:{script:{get run(){let success,failure;const r={withSuccessHandler(f){success=f;return r;},withFailureHandler(f){failure=f;return r;},getRecentEntries(...args){calls.push({method:'feed',args,success,failure});},verifyToken(...args){calls.push({method:'auth',args,success,failure});}};return r;}}}});
 vm.runInContext(html.slice(html.indexOf('function loadFeed(reset){'),html.indexOf('\nfunction loadMoreFeed()',html.indexOf('function loadFeed(reset){'))),c);return {c,calls,list,more};}
test('baseline drops a refresh while reading; candidate queues a fresh head and suppresses stale data',()=>{for(const [html,fixed] of [[baseline,false],[candidate,true]]){const h=harness(html);h.c.loadFeed();h.c.loadFeed();h.calls[0].success([{id:'older'}]);assert.equal(h.calls.length,fixed?2:1);if(fixed){assert(!h.list.innerHTML.includes('older'));h.calls[1].success([{id:'newest'}]);assert.equal(h.list.innerHTML,'newest');}else assert.equal(h.list.innerHTML,'older');}});
test('queued reset during pagination requests offset zero and does not append an old page',()=>{const h=harness(candidate);h.c.feedEntries=[{id:'head'}];h.c._feedOffset=12;h.c.loadFeed(false);assert.equal(h.calls[0].args[2],12);h.c.loadFeed(true);h.calls[0].success([{id:'old-page'}]);assert.equal(h.calls[1].args[2],0);h.calls[1].success([{id:'new-head'}]);assert.equal(h.list.innerHTML,'new-head');assert.equal(h.c._feedOffset,1);});
test('malformed/auth error responses are errors, never an empty diary success',()=>{for(const response of [{success:false,code:'E_AUTH'},{items:[]},null]){const h=harness(candidate);h.c.loadFeed();h.calls[0].success(response);assert(!h.list.innerHTML.includes('일기가 없어요'));assert.match(h.list.innerHTML,/로그인|불러오지 못/);assert.equal(h.c._feedLoading,false);}});
test('legacy empty array verifies teacher session; valid empty remains empty',()=>{for(const auth of [{success:false},{success:true,role:'학생'},{success:true,role:'선생님'}]){const h=harness(candidate);h.c.loadFeed();h.calls[0].success([]);assert.equal(h.calls[1].method,'auth');h.calls[1].success(auth);assert.equal(h.c._feedLoading,false);if(auth.role==='선생님')assert.equal(h.list.innerHTML,'');else assert.match(h.list.innerHTML,/로그인이 만료/);}});
test('stale account callback cannot replace a newer feed or release its loading flag',()=>{const h=harness(candidate);h.c.loadFeed();h.c._feedRequestGeneration++;h.c.currentUser={name:'다른 가상교사',role:'선생님'};h.c.feedEntries=[{id:'other-owner'}];h.c._feedLoading=true;h.calls[0].success([{id:'prior-owner'}]);assert.equal(h.c.feedEntries[0].id,'other-owner');assert.equal(h.c._feedLoading,true);});
test('failed additional-page load restores retry button and retains loaded records',()=>{const h=harness(candidate);h.c.feedEntries=[{id:'kept'}];h.c.loadFeed(false);h.calls[0].failure(new Error('network'));assert.equal(h.more.disabled,false);assert.equal(h.c.feedEntries[0].id,'kept');});
