import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
const base='http://127.0.0.1:3020';
async function call(token,method,args=[],extra={}){const r=await fetch(base+'/api/rpc',{method:'POST',headers:{Origin:base,'Content-Type':'application/json','X-OKGU-Request':'1',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify({method,args,requestId:randomUUID(),...extra})});return {status:r.status,value:await r.json()};}
const login=async name=>{const r=await call('','login',[name,'0042',false]);assert.equal(r.status,200);return r.value.token;};
let a,b,t;test.before(async()=>{[a,b,t]=await Promise.all(['시험학생11','시험학생12','가상교사'].map(login));});
const day=new Date().toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'}),args=(body='가상 권한 검사',priv=false,pub=false,refs=[])=>['위조 이름',day,'😄','신남','#111',body,false,pub,priv,JSON.stringify(refs),''];
test('anonymous and foreign origin access denied',async()=>{assert.equal((await call('','getMyEntries')).status,401);const r=await fetch(base+'/api/rpc',{method:'POST',headers:{Origin:'https://untrusted.example','X-OKGU-Request':'1'},body:'{}'});assert.equal(r.status,403);});
test('identity derives from session; private diary hidden from teacher and peer',async()=>{const saved=await call(a,'saveEntry',args('가상 개인 기록',true));assert.equal(saved.status,200);assert.equal(saved.value.entry.studentName,'시험학생11');for(const token of [b,t])assert.equal((await call(token,'getEntry',[saved.value.id])).status,404);assert.equal((await call(a,'getEntry',[saved.value.id])).status,200);});
test('teacher-only versus class access applies to diary, board and photo',async()=>{const r=await fetch(base+'/api/photos',{method:'POST',headers:{Origin:base,Authorization:'Bearer '+a,'X-Request-Id':randomUUID()},body:await readFile('fixtures/photo.png')});assert.equal(r.status,200);const photo=(await r.json()).url;const saved=(await call(a,'saveEntry',args('가상 공유 사진',false,false,[photo]))).value;assert.equal((await call(t,'getEntry',[saved.id])).status,200);assert.equal((await call(b,'getEntry',[saved.id])).status,404);const id=photo.slice(11);for(const [token,status] of [[a,200],[t,200],[b,404],['',401]])assert.equal((await fetch(base+'/api/photos/'+id,{headers:{Authorization:'Bearer '+token}})).status,status);const entry=(await call(a,'getEntry',[saved.id])).value;const editArgs=args('가상 공유 사진',false,true,[photo]);editArgs[10]=saved.id;assert.equal((await call(a,'saveEntry',editArgs,{expectedVersion:entry.version})).status,200);assert.equal((await call(b,'getEntry',[saved.id])).status,200);assert.equal((await fetch(base+'/api/photos/'+id,{headers:{Authorization:'Bearer '+b}})).status,200);});
test('concurrent retries create one diary and stable receipt; payload reuse fails',async()=>{const requestId=randomUUID(),payload=args();const rows=await Promise.all(Array.from({length:5},()=>call(a,'saveEntry',payload,{requestId})));assert(rows.every(r=>r.status===200));assert.equal(new Set(rows.map(r=>r.value.id)).size,1);const changed=[...payload];changed[5]='다른 본문';assert.equal((await call(a,'saveEntry',changed,{requestId})).status,409);});
test('cross-device version conflict permits exactly one edit',async()=>{const saved=(await call(a,'saveEntry',args())).value;const payload=args('변경');payload[10]=saved.id;const rows=await Promise.all([call(a,'saveEntry',payload,{expectedVersion:1}),call(a,'saveEntry',payload,{expectedVersion:1})]);assert.deepEqual(rows.map(r=>r.status).sort(),[200,409]);assert.equal((await call(a,'getEntry',[saved.id])).value.version,2);});
test('student cannot invoke teacher dashboard or impersonate teacher comment',async()=>{assert.equal((await call(a,'getTeacherDashboardBundle')).status,403);const saved=(await call(a,'saveEntry',args())).value;assert.equal((await call(a,'addTeacherComment',['위조',saved.id,'교사 위조'])).status,403);const c=(await call(t,'addTeacherComment',['',saved.id,'가상 교사 댓글'])).value;assert.equal((await call(a,'editTeacherComment',['',c.id,'위조 수정'])).status,403);assert.equal((await call(a,'addStudentReplyToDiary',[saved.id,'','가상 답글',c.id])).status,200);assert.equal((await call(t,'deleteTeacherComment',['',c.id])).status,200);assert.equal((await call(a,'getEntry',[saved.id])).value.teacherComments.some(c=>c.text==='가상 교사 댓글'),false);});
test('likes are idempotent; visibility change revokes board access',async()=>{const saved=(await call(a,'saveEntry',args('가상 게시판',false,true))).value;const requestId=randomUUID();const x=await call(b,'toggleLike',[saved.id],{requestId}),y=await call(b,'toggleLike',[saved.id],{requestId});assert.deepEqual(x.value,y.value);assert.equal(x.value.liked,true);assert.equal((await call(b,'toggleLike',[saved.id])).value.liked,false);const payload=args('가상 게시판',true);payload[10]=saved.id;assert.equal((await call(a,'saveEntry',payload,{expectedVersion:1})).status,200);assert.equal((await call(b,'toggleLike',[saved.id])).status,404);});
test('praise approval, anonymity and teacher counsel restrictions',async()=>{const p=(await call(a,'sendPraise',['위조','시험학생12','가상 칭찬',true])).value;assert.equal((await call(b,'getPraise')).value.received.some(x=>x.id===p.id),false);assert.equal((await call(a,'setPraiseStatus',['',p.id,'approved'])).status,403);assert.equal((await call(t,'setPraiseStatus',['',p.id,'approved'])).status,200);assert.equal((await call(b,'getPraise')).value.received.find(x=>x.id===p.id).from,'익명');assert.equal((await call(a,'setStudentCounselFlag',['','시험학생12',true,'가상 메모'])).status,403);assert.equal((await call(t,'setStudentCounselFlag',['','시험학생12',true,'가상 메모'])).status,200);assert.equal((await call(t,'listStudentFlags')).value.flags['시험학생12'].counsel,true);});
test('photo type, size, upload ownership and trial push restriction',async()=>{assert.equal((await fetch(base+'/api/photos',{method:'POST',headers:{Origin:base,Authorization:'Bearer '+a,'X-Request-Id':randomUUID()},body:'invalid'})).status,415);assert.equal((await fetch(base+'/api/photos',{method:'POST',headers:{Origin:base,Authorization:'Bearer '+a,'X-Request-Id':randomUUID()},body:new Uint8Array(1048577)})).status,413);const r=await fetch(base+'/api/photos',{method:'POST',headers:{Origin:base,Authorization:'Bearer '+a,'X-Request-Id':randomUUID()},body:await readFile('fixtures/photo.png')});const photo=(await r.json()).url;assert.equal((await call(b,'saveEntry',args('도용 검사',false,false,[photo]))).status,404);assert.equal((await call(a,'sendTestPush')).value.code,'E_PUSH_DISABLED');});
test('logout revokes token and clears server access',async()=>{const token=await login('시험학생13');assert.equal((await call(token,'logout')).status,200);assert.equal((await call(token,'getMyEntries')).status,401);});
