PRAGMA foreign_keys=ON;
CREATE TABLE classes(id TEXT PRIMARY KEY,label TEXT NOT NULL);
CREATE TABLE accounts(id TEXT PRIMARY KEY,legacy_identity TEXT NOT NULL UNIQUE,display_name TEXT NOT NULL,class_id TEXT NOT NULL REFERENCES classes(id),role TEXT NOT NULL CHECK(role IN('student','teacher')),active INTEGER NOT NULL DEFAULT 1,UNIQUE(id,class_id));
CREATE TABLE credentials(account_id TEXT PRIMARY KEY REFERENCES accounts(id),login_name TEXT NOT NULL UNIQUE,pin_hash TEXT NOT NULL);
CREATE TABLE sessions(token_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id),expires_at INTEGER NOT NULL);
CREATE INDEX session_account ON sessions(account_id);
CREATE TABLE login_attempts(key TEXT PRIMARY KEY,attempts INTEGER NOT NULL,window_start INTEGER NOT NULL);
CREATE TABLE diaries(id TEXT PRIMARY KEY,legacy_id TEXT UNIQUE,author_id TEXT NOT NULL,class_id TEXT NOT NULL,diary_date TEXT NOT NULL,body TEXT NOT NULL CHECK(length(body) BETWEEN 1 AND 2000),mood_emoji TEXT NOT NULL,mood_label TEXT NOT NULL,mood_color TEXT NOT NULL,visibility TEXT NOT NULL CHECK(visibility IN('private','teacher','class')),legacy_secret INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL,version INTEGER NOT NULL DEFAULT 1,deleted_at INTEGER,last_request_id TEXT,source_batch TEXT,FOREIGN KEY(author_id,class_id) REFERENCES accounts(id,class_id));
CREATE INDEX diary_author_page ON diaries(author_id,diary_date DESC,id DESC) WHERE deleted_at IS NULL;
CREATE INDEX diary_class_page ON diaries(class_id,visibility,diary_date DESC,id DESC) WHERE deleted_at IS NULL;
CREATE TABLE photo_uploads(id TEXT PRIMARY KEY,owner_id TEXT NOT NULL REFERENCES accounts(id),object_path TEXT UNIQUE NOT NULL,source_sha256 TEXT NOT NULL,sha256 TEXT NOT NULL,byte_size INTEGER NOT NULL,mime_type TEXT NOT NULL,created_at INTEGER NOT NULL,ready INTEGER NOT NULL DEFAULT 0,diary_id TEXT REFERENCES diaries(id));
CREATE TABLE attachments(id TEXT PRIMARY KEY,diary_id TEXT NOT NULL REFERENCES diaries(id),object_path TEXT NOT NULL,ordinal INTEGER NOT NULL,sha256 TEXT NOT NULL,byte_size INTEGER NOT NULL,mime_type TEXT NOT NULL,legacy_file_id TEXT,UNIQUE(diary_id,ordinal));
CREATE INDEX attachment_diary ON attachments(diary_id,ordinal);
CREATE TABLE receipts(account_id TEXT NOT NULL REFERENCES accounts(id),request_id TEXT NOT NULL,payload_hash TEXT NOT NULL,nonce TEXT NOT NULL,result TEXT NOT NULL,created_at INTEGER NOT NULL,PRIMARY KEY(account_id,request_id));
CREATE TABLE board_posts(id TEXT PRIMARY KEY,legacy_id TEXT UNIQUE,diary_id TEXT UNIQUE REFERENCES diaries(id),author_id TEXT NOT NULL REFERENCES accounts(id),body TEXT NOT NULL,mood TEXT,date_label TEXT,created_at INTEGER NOT NULL,deleted_at INTEGER,last_request_id TEXT);
CREATE INDEX board_page ON board_posts(created_at DESC,id DESC) WHERE deleted_at IS NULL;
CREATE TABLE board_comments(id TEXT PRIMARY KEY,legacy_id TEXT UNIQUE,post_id TEXT NOT NULL REFERENCES board_posts(id),author_id TEXT NOT NULL REFERENCES accounts(id),body TEXT NOT NULL,created_at INTEGER NOT NULL,parent_id TEXT REFERENCES board_comments(id),deleted_at INTEGER,last_request_id TEXT);
CREATE TABLE diary_comments(id TEXT PRIMARY KEY,legacy_id TEXT UNIQUE,diary_id TEXT NOT NULL REFERENCES diaries(id),author_id TEXT NOT NULL REFERENCES accounts(id),body TEXT NOT NULL,created_at INTEGER NOT NULL,parent_id TEXT REFERENCES diary_comments(id),deleted_at INTEGER,last_request_id TEXT);
CREATE INDEX comments_post ON board_comments(post_id,created_at);
CREATE INDEX comments_diary ON diary_comments(diary_id,created_at);
CREATE TABLE board_likes(post_id TEXT NOT NULL REFERENCES board_posts(id),account_id TEXT NOT NULL REFERENCES accounts(id),last_request_id TEXT,PRIMARY KEY(post_id,account_id));
CREATE TABLE praises(id TEXT PRIMARY KEY,legacy_id TEXT UNIQUE,sender_id TEXT NOT NULL REFERENCES accounts(id),recipient_id TEXT NOT NULL REFERENCES accounts(id),body TEXT NOT NULL,created_at INTEGER NOT NULL,is_read INTEGER NOT NULL DEFAULT 0,anonymous INTEGER NOT NULL DEFAULT 0,hidden INTEGER NOT NULL DEFAULT 0,approval TEXT NOT NULL CHECK(approval IN('pending','approved','rejected')),deleted_at INTEGER,last_request_id TEXT);
CREATE INDEX praise_recipient ON praises(recipient_id,approval,created_at DESC);
CREATE TABLE teacher_notes(student_id TEXT PRIMARY KEY REFERENCES accounts(id),needs_counsel INTEGER NOT NULL,memo TEXT NOT NULL,setter_id TEXT NOT NULL REFERENCES accounts(id),set_at INTEGER NOT NULL,last_request_id TEXT);
CREATE TABLE notifications(id TEXT PRIMARY KEY,recipient_id TEXT NOT NULL REFERENCES accounts(id),actor_id TEXT NOT NULL REFERENCES accounts(id),event_key TEXT NOT NULL,type TEXT NOT NULL,link_id TEXT,comment_id TEXT,created_at INTEGER NOT NULL,UNIQUE(recipient_id,event_key));
CREATE INDEX notification_recipient ON notifications(recipient_id,created_at DESC);
CREATE TABLE push_subscriptions(endpoint_hash TEXT PRIMARY KEY,account_id TEXT NOT NULL REFERENCES accounts(id),subscription TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1,updated_at INTEGER NOT NULL,last_request_id TEXT);
CREATE TABLE push_jobs(id TEXT PRIMARY KEY,event_key TEXT NOT NULL UNIQUE,account_id TEXT NOT NULL REFERENCES accounts(id),payload TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'pending',attempts INTEGER NOT NULL DEFAULT 0,created_at INTEGER NOT NULL,updated_at INTEGER NOT NULL);
CREATE TABLE migration_records(source_id TEXT NOT NULL,entity TEXT NOT NULL,legacy_id TEXT NOT NULL,target_id TEXT NOT NULL,source_hash TEXT NOT NULL,target_hash TEXT,batch_id TEXT NOT NULL,status TEXT NOT NULL,PRIMARY KEY(source_id,entity,legacy_id));
CREATE TABLE source_archive(batch_id TEXT NOT NULL,entity TEXT NOT NULL,legacy_id TEXT NOT NULL,payload TEXT NOT NULL,PRIMARY KEY(batch_id,entity,legacy_id));
