import {browserOptions} from './lib/browser-options.mjs';
import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const origin=process.env.OKGU_TRIAL_FRONTEND_ORIGIN||process.env.OKGU_TRIAL_API_ORIGIN||'http://127.0.0.1:3020';
const base=origin+'/okgu-diary-alarm-/';
const browser=await chromium.launch(browserOptions(origin));
const capture=async(page,name)=>{if(process.env.OKGU_UI_CAPTURE_DIR){await mkdir(process.env.OKGU_UI_CAPTURE_DIR,{recursive:true});await page.screenshot({path:process.env.OKGU_UI_CAPTURE_DIR+'/'+name+'.png',fullPage:true});}};
const paginationMarker='브라우저 페이지 가상 '+crypto.randomUUID();
const results=[];const measure=async(name,fn)=>{const t=performance.now();await fn();results.push({name,ms:Math.round(performance.now()-t),result:'passed'});console.log('PASS:',name);};
try{
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Seoul'});const page=await context.newPage();const errors=[],rpcMethods=[];let external=0;let paginationIds=[];
 page.on('pageerror',e=>{errors.push(e.message);console.error(e.stack);});page.on('request',r=>{if(r.url().endsWith('/api/rpc')){try{rpcMethods.push(JSON.parse(r.postData()).method);}catch{}}});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(![...(['127.0.0.1','localhost'].includes(new URL(origin).hostname)?['127.0.0.1','localhost']:[]),new URL(origin).hostname,...(process.env.OKGU_TRIAL_API_ORIGIN?[new URL(process.env.OKGU_TRIAL_API_ORIGIN).hostname]:[])].includes(u.hostname)&&u.protocol.startsWith('http')){external++;return route.abort();}return route.continue();});
 await measure('first visit and original login UI',async()=>{await page.goto(base);assert.equal(await page.title(),'OKGU DIARY');assert(await page.locator('#login-screen').isVisible());await page.locator('#login-btn').click();assert.equal(await page.locator('#login-err').textContent(),'이름을 입력해줘');});
 page.on('dialog',d=>d.dismiss());
 await measure('login with zero-prefixed PIN; no GAS request',async()=>{await page.locator('#li-name').fill('시험학생01');await page.locator('#li-pin').fill('0042');await page.locator('#login-btn').click();await page.locator('#main-app').waitFor({state:'visible'});await page.waitForFunction(()=>currentUser&&currentUser.name==='시험학생01');await page.locator('#custom-confirm-modal').waitFor({state:'visible'});await page.locator('#custom-confirm-cancel').click();assert.equal(external,0);await capture(page,'student-write');});
 await measure('text save committed then UI success',async()=>{await page.locator('#diary-text').fill('브라우저 가상 기록');await page.locator('#save-btn').click();await page.waitForFunction(()=>document.getElementById('save-msg').style.display==='block');assert.equal(await page.locator('#diary-text').inputValue(),'');await page.waitForFunction(()=>myEntries.some(e=>e.text==='브라우저 가상 기록'));});
 await measure('quick diary saves through same authenticated server',async()=>{await page.evaluate(()=>switchWriteMode('quick'));await page.locator('#quick-line').fill('가상 한 줄 기록');await page.locator('.quick-save').click();await page.waitForFunction(()=>document.getElementById('quick-line').value==='');await page.evaluate(()=>switchWriteMode('full'));});
 await measure('binary photo upload and diary save',async()=>{await page.locator('#diary-text').fill('사진 포함 가상 기록');await page.locator('input[type=file]').first().setInputFiles('fixtures/photo.png');await page.waitForFunction(()=>pendingPhotos.length===1);await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0,{},{timeout:30000});await page.waitForFunction(()=>myEntries.some(e=>e.text==='사진 포함 가상 기록'&&e.photos.length===1));});
 await measure('photo edit retains existing attachment',async()=>{await page.evaluate(()=>editDiary(myEntries.find(e=>e.text==='사진 포함 가상 기록')));assert.equal(await page.evaluate(()=>pendingPhotos.length),1);await page.locator('#diary-text').fill('사진 보존 수정');await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0);await page.waitForFunction(()=>myEntries.some(e=>e.text==='사진 보존 수정'&&e.photos.length===1));});
 await measure('failed save preserves text and attachment; retry',async()=>{await page.locator('#diary-text').fill('실패 후 보존');await page.locator('input[type=file]').first().setInputFiles('fixtures/photo.png');await page.waitForFunction(()=>pendingPhotos.length===1);await page.route('**/api/rpc',route=>{const data=JSON.parse(route.request().postData());if(data.method==='saveEntry')return route.abort();return route.continue();});await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress);assert.equal(await page.locator('#diary-text').inputValue(),'실패 후 보존');assert.equal(await page.evaluate(()=>pendingPhotos.length),1);await page.unroute('**/api/rpc');await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0);});
 await measure('search queries server; stat/calendar and authenticated photo load',async()=>{await page.evaluate(()=>goTo('search','검색','',navButtonFor('search')));await page.locator('#search-input').fill('사진 보존');await page.locator('.search-btn').click();await page.waitForFunction(()=>document.getElementById('search-results').textContent.includes('사진 보존 수정'));await page.evaluate(()=>goTo('stat','통계','',navButtonFor('stat')));await page.waitForFunction(()=>document.getElementById('stat-cal-card').querySelector('.mini-cal'));await page.evaluate(()=>showStatDay(todayKey()));await page.waitForFunction(()=>Array.from(document.querySelectorAll('img[data-okgu-photo]')).some(img=>img.getAttribute('src')?.startsWith('blob:')));await capture(page,'student-stat');});
 await measure('search more button loads all fifty-one matching records',async()=>{paginationIds=await page.evaluate(async marker=>{const ids=[];for(let n=0;n<51;n++){const result=await OKGUAPI.call('saveEntry',[currentUser.name,todayKey(),'😄','신남','#111',marker+' '+n,false,false,false,'[]','']);ids.push(result.id);}return ids;},paginationMarker);await page.evaluate(()=>goTo('search','검색','',navButtonFor('search')));await page.locator('#search-input').fill(paginationMarker);await page.locator('#scr-search .search-btn').first().click();await page.locator('[data-okgu-more=search]').waitFor();assert.equal(await page.locator('#search-results .sentry').count(),50);await page.locator('[data-okgu-more=search]').click();await page.waitForFunction(()=>document.querySelectorAll('#search-results .sentry').length===51);assert.equal(await page.locator('[data-okgu-more=search]').count(),0);});
 await measure('yearbook opens synchronously and waits for authenticated photos',async()=>{const popupPromise=page.waitForEvent('popup');await page.evaluate(()=>printMyYearbook());const popup=await popupPromise;await popup.waitForFunction(()=>document.querySelector('.yprintbar button')&&!document.querySelector('.yprintbar button').disabled,{},{timeout:30000});assert((await popup.locator('body').textContent()).includes('사진 보존 수정'));assert.equal(await popup.evaluate(()=>[...document.images].every(i=>i.complete&&i.naturalWidth>0)),true);await popup.close();});
 await measure('offline save keeps draft; reconnection permits retry',async()=>{await page.evaluate(()=>goTo('write','일기 쓰기','',navButtonFor('write')));await page.locator('#diary-text').fill('오프라인 가상 초안');await context.setOffline(true);await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress);assert.equal(await page.locator('#diary-text').inputValue(),'오프라인 가상 초안');await context.setOffline(false);await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&document.getElementById('diary-text').value==='');});
 await measure('PWA registration retains scope and does not cache account data',async()=>{const registration=await page.evaluate(async()=>{const r=await navigator.serviceWorker.ready;return {scope:r.scope,url:r.active.scriptURL};});assert.equal(registration.scope,base);assert.equal(registration.url,base+'sw.js');await page.locator('#diary-text').fill('업데이트 중 가상 초안');await page.evaluate(async()=>{const r=await navigator.serviceWorker.getRegistration();await r.update();});assert.equal(await page.locator('#diary-text').inputValue(),'업데이트 중 가상 초안');assert.equal(await page.evaluate(async()=>{const keys=await caches.keys();return keys.length;}),0);await page.locator('#diary-text').fill('');});
 await measure('revisit restores session; logout/account switch isolates data',async()=>{await page.reload();await page.locator('#main-app').waitFor({state:'visible'});await page.locator('#custom-confirm-modal').waitFor({state:'visible'});await page.locator('#custom-confirm-cancel').click();const previousToken=await page.evaluate(()=>OKGUAPI.getToken());await page.evaluate(()=>doLogout());await page.locator('#custom-confirm-ok').click();await page.locator('#login-screen').waitFor({state:'visible'});await page.waitForFunction(async token=>(await fetch(OKGU_CONFIG.apiOrigin+'/api/rpc',{method:'POST',headers:{'Content-Type':'application/json','X-OKGU-Request':'1',Authorization:'Bearer '+token},body:JSON.stringify({method:'verifyToken',args:[]})})).status===401,previousToken,{timeout:10000,polling:200});assert(await page.locator('#login-screen').isVisible());await page.locator('#li-name').fill('시험학생02');await page.locator('#li-pin').fill('0042');await page.locator('#login-btn').click();await page.locator('#main-app').waitFor({state:'visible'});await page.waitForFunction(()=>currentUser.name==='시험학생02');assert.equal(await page.evaluate(()=>myEntries.some(e=>e.studentName==='시험학생01')),false);assert.equal(await page.locator('#teacher-nav-btn').count(),0);});
 await context.close();
 const teacherContext=await browser.newContext({viewport:{width:1365,height:900},timezoneId:'Asia/Seoul'});const tp=await teacherContext.newPage();tp.on('pageerror',e=>{errors.push(e.message);console.error(e.stack);});tp.on('dialog',d=>d.dismiss());
 await measure('teacher dashboard uses one bundle and existing renderers',async()=>{await tp.goto(base);await tp.locator('#li-name').fill('가상교사');await tp.locator('#li-pin').fill('0042');await tp.locator('#login-btn').click();await tp.locator('#main-app').waitFor({state:'visible'});await tp.locator('#custom-confirm-modal').waitFor({state:'visible'});await tp.locator('#custom-confirm-cancel').click();await tp.evaluate(()=>goTo('dash','교사 대시보드','학급 현황',navButtonFor('dash')));await tp.waitForFunction(()=>classOverview.length>=13);assert.equal(await tp.locator('#ds-total').textContent(),'15');await capture(tp,'teacher-feed');await tp.locator('[data-tsub=students]').click();await capture(tp,'teacher-students');await tp.evaluate(()=>openStudentDiary('시험학생01'));await tp.locator('#modal-diary-list .diary-item').first().waitFor();});
 await measure('teacher student modal loads a second page and retains comment draft',async()=>{await tp.locator('[data-okgu-more=student]').waitFor();const input=tp.locator('#modal-diary-list input:visible').first();const id=await input.getAttribute('id');await input.fill('교사 가상 미전송 초안');const before=await tp.locator('#modal-diary-list .diary-item').count();await tp.locator('[data-okgu-more=student]').click();await tp.waitForFunction(n=>document.querySelectorAll('#modal-diary-list .diary-item').length>n,before);assert.equal(await tp.locator('[id="'+id+'"]').inputValue(),'교사 가상 미전송 초안');assert((await tp.locator('#modal-diary-list').textContent()).includes('사진 보존 수정'));});
 // Remove only this suite's synthetic pagination rows.
 const cleanup=await teacherContext.newPage();await cleanup.goto(base);await cleanup.evaluate(async ids=>{const res=await OKGUAPI.call('login',['시험학생01','0042',false]);for(const id of ids)await OKGUAPI.call('deleteEntry',['',id],{expectedVersion:1});},paginationIds);await cleanup.close();
 await measure('no JavaScript exceptions and no chunking/GAS calls',async()=>{assert.deepEqual(errors,[]);assert(!rpcMethods.includes('uploadPhotoChunk'));assert.equal(external,0);});
 await mkdir('artifacts',{recursive:true});await writeFile('artifacts/브라우저_검증_2026-10-02.json',JSON.stringify({environment:origin.includes('127.0.0.1')?'local workerd emulation; NOT deployed measurements':'deployed Cloudflare trial',frontendOrigin:origin,browser:'Linux Chromium; viewport only, not physical mobile devices',results,rpcMethods},null,2));
 await teacherContext.close();
}finally{await browser.close();}
