import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir,writeFile} from 'node:fs/promises';
const base='http://127.0.0.1:3020/okgu-diary-alarm-/';
const browser=await chromium.launch({executablePath:process.env.CHROME_PATH||'/usr/bin/chromium',args:['--no-sandbox']});
const results=[];const measure=async(name,fn)=>{const t=performance.now();await fn();results.push({name,ms:Math.round(performance.now()-t),result:'passed'});console.log('PASS:',name);};
try{
 const context=await browser.newContext({viewport:{width:390,height:844},timezoneId:'Asia/Seoul'});const page=await context.newPage();const errors=[],rpcMethods=[];let external=0;
 page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(r.url().endsWith('/api/rpc')){try{rpcMethods.push(JSON.parse(r.postData()).method);}catch{}}});
 await context.route('**/*',route=>{const u=new URL(route.request().url());if(!['127.0.0.1','localhost'].includes(u.hostname)&&u.protocol.startsWith('http')){external++;return route.abort();}return route.continue();});
 await measure('first visit and original login UI',async()=>{await page.goto(base);assert.equal(await page.title(),'OKGU DIARY');assert(await page.locator('#login-screen').isVisible());await page.locator('#login-btn').click();assert.equal(await page.locator('#login-err').textContent(),'이름을 입력해줘');});
 page.on('dialog',d=>d.dismiss());
 await measure('login with zero-prefixed PIN; no GAS request',async()=>{await page.locator('#li-name').fill('시험학생01');await page.locator('#li-pin').fill('0042');await page.locator('#login-btn').click();await page.locator('#main-app').waitFor({state:'visible'});await page.waitForFunction(()=>currentUser&&currentUser.name==='시험학생01');await page.locator('#custom-confirm-modal').waitFor({state:'visible'});await page.locator('#custom-confirm-cancel').click();assert.equal(external,0);});
 await measure('text save committed then UI success',async()=>{await page.locator('#diary-text').fill('브라우저 가상 기록');await page.locator('#save-btn').click();await page.waitForFunction(()=>document.getElementById('save-msg').style.display==='block');assert.equal(await page.locator('#diary-text').inputValue(),'');await page.waitForFunction(()=>myEntries.some(e=>e.text==='브라우저 가상 기록'));});
 await measure('quick diary saves through same authenticated server',async()=>{await page.evaluate(()=>switchWriteMode('quick'));await page.locator('#quick-line').fill('가상 한 줄 기록');await page.locator('.quick-save').click();await page.waitForFunction(()=>document.getElementById('quick-line').value==='');await page.evaluate(()=>switchWriteMode('full'));});
 await measure('binary photo upload and diary save',async()=>{await page.locator('#diary-text').fill('사진 포함 가상 기록');await page.locator('input[type=file]').first().setInputFiles('fixtures/photo.png');await page.waitForFunction(()=>pendingPhotos.length===1);await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0,{},{timeout:30000});await page.waitForFunction(()=>myEntries.some(e=>e.text==='사진 포함 가상 기록'&&e.photos.length===1));});
 await measure('photo edit retains existing attachment',async()=>{await page.evaluate(()=>editDiary(myEntries.find(e=>e.text==='사진 포함 가상 기록')));assert.equal(await page.evaluate(()=>pendingPhotos.length),1);await page.locator('#diary-text').fill('사진 보존 수정');await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0);await page.waitForFunction(()=>myEntries.some(e=>e.text==='사진 보존 수정'&&e.photos.length===1));});
 await measure('failed save preserves text and attachment; retry',async()=>{await page.locator('#diary-text').fill('실패 후 보존');await page.locator('input[type=file]').first().setInputFiles('fixtures/photo.png');await page.waitForFunction(()=>pendingPhotos.length===1);await page.route('**/api/rpc',route=>{const data=JSON.parse(route.request().postData());if(data.method==='saveEntry')return route.abort();return route.continue();});await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress);assert.equal(await page.locator('#diary-text').inputValue(),'실패 후 보존');assert.equal(await page.evaluate(()=>pendingPhotos.length),1);await page.unroute('**/api/rpc');await page.locator('#save-btn').click();await page.waitForFunction(()=>!_saveInProgress&&pendingPhotos.length===0);});
 await measure('search queries server; stat/calendar and authenticated photo load',async()=>{await page.evaluate(()=>goTo('search','검색','',navButtonFor('search')));await page.locator('#search-input').fill('사진 보존');await page.locator('.search-btn').click();await page.waitForFunction(()=>document.getElementById('search-results').textContent.includes('사진 보존 수정'));await page.evaluate(()=>goTo('stat','통계','',navButtonFor('stat')));await page.waitForFunction(()=>document.getElementById('stat-cal-card').querySelector('.mini-cal'));await page.evaluate(()=>showStatDay(todayKey()));await page.waitForFunction(()=>Array.from(document.querySelectorAll('img[data-okgu-photo]')).some(img=>img.getAttribute('src')?.startsWith('blob:')));});
 await measure('revisit restores session; logout/account switch isolates data',async()=>{await page.reload();await page.locator('#main-app').waitFor({state:'visible'});await page.locator('#custom-confirm-modal').waitFor({state:'visible'});await page.locator('#custom-confirm-cancel').click();await page.evaluate(()=>OKGUAPI.call('logout',[]));await page.reload();assert(await page.locator('#login-screen').isVisible());await page.locator('#li-name').fill('시험학생02');await page.locator('#li-pin').fill('0042');await page.locator('#login-btn').click();await page.locator('#main-app').waitFor({state:'visible'});await page.waitForFunction(()=>currentUser.name==='시험학생02');assert.equal(await page.evaluate(()=>myEntries.some(e=>e.studentName==='시험학생01')),false);assert.equal(await page.locator('#teacher-nav-btn').count(),0);});
 await context.close();
 const teacherContext=await browser.newContext({viewport:{width:1365,height:900},timezoneId:'Asia/Seoul'});const tp=await teacherContext.newPage();tp.on('pageerror',e=>errors.push(e.message));tp.on('dialog',d=>d.dismiss());
 await measure('teacher dashboard uses one bundle and existing renderers',async()=>{await tp.goto(base);await tp.locator('#li-name').fill('가상교사');await tp.locator('#li-pin').fill('0042');await tp.locator('#login-btn').click();await tp.locator('#main-app').waitFor({state:'visible'});await tp.locator('#custom-confirm-modal').waitFor({state:'visible'});await tp.locator('#custom-confirm-cancel').click();await tp.evaluate(()=>goTo('dash','교사 대시보드','학급 현황',navButtonFor('dash')));await tp.waitForFunction(()=>classOverview.length>=13);assert.equal(await tp.locator('#ds-total').textContent(),'15');await tp.evaluate(()=>openStudentDiary('시험학생01'));await tp.waitForFunction(()=>document.getElementById('modal-diary-list').textContent.includes('사진 보존 수정'));});
 await measure('no JavaScript exceptions and no chunking/GAS calls',async()=>{assert.deepEqual(errors,[]);assert(!rpcMethods.includes('uploadPhotoChunk'));assert.equal(external,0);});
 await mkdir('artifacts',{recursive:true});await writeFile('artifacts/브라우저_검증_2026-10-02.json',JSON.stringify({browser:'Linux Chromium; viewport only, not physical mobile devices',results,rpcMethods},null,2));
 await teacherContext.close();
}finally{await browser.close();}
