// Offline private-file-only adapter. No Google/Cloudflare calls or imports.
import {readFile,writeFile,mkdir,realpath} from 'node:fs/promises';import path from 'node:path';
import {normalizeExport} from '../migration/normalize.ts';import {plan,sha,sourceFields} from '../migration/core.ts';
const local=await realpath('.local');
async function privatePath(input){const file=await realpath(input);if(!file.startsWith(local+path.sep))throw Error('PRIVATE_LOCAL_PATH_REQUIRED');return file;}
try{
 const sourcePath=await privatePath(process.argv[2]),identityPath=await privatePath(process.argv[3]);const raw=JSON.parse(await readFile(sourcePath,'utf8')),identity=JSON.parse(await readFile(identityPath,'utf8'));
 if(raw.format!=='okgu-sheet-raw-export-v1'||!raw.complete||!identity.reviewed||!identity.capturedSourceHash||identity.capturedSourceHash!==sha(await readFile(sourcePath)))throw Error('REVIEWED_RAW_SOURCE_FINGERPRINT_REQUIRED');
 const sheets={};for(const [name,s] of Object.entries(raw.sheets)){if(!sourceFields[name])throw Error('UNKNOWN_SHEET_REQUIRES_ARCHIVE_REVIEW');if(!identity.columns?.[name])throw Error('ALL_SOURCE_SHEETS_REQUIRE_REVIEW');sheets[name]={headers:s.headers,rows:s.rows.map(row=>row.map((v,i)=>{if(v&&typeof v==='object'){if(v.type!=='date'||!Number.isFinite(Date.parse(v.iso)))throw Error('SOURCE_TYPE_REVIEW_REQUIRED');const kind=identity.columnKinds?.[name]?.[s.headers[i]];if(kind==='timestamp')return new Date(v.iso).toISOString();if(kind==='day'&&identity.timeZone===raw.timeZone)return new Intl.DateTimeFormat('en-CA',{timeZone:raw.timeZone,year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date(v.iso));throw Error('DATE_KIND_REVIEW_REQUIRED');}return v;}))};}
 const files=[];for(const f of raw.files||[]){const location=await privatePath(path.resolve(path.dirname(sourcePath),f.path));const bytes=await readFile(location);if(sha(bytes)!==f.sha256||bytes.length!==f.size)throw Error('ORIGINAL_PHOTO_MISMATCH');files.push({...f,path:path.relative(process.cwd(),location)});}
 const snapshot=await normalizeExport({...raw,format:'okgu-sheet-export-v1',sheets,files},identity),checked=plan(snapshot);if(checked.issues.length)throw Error('SOURCE_SCHEMA_IDENTITY_RELATION_REVIEW_REQUIRED');
 const directory=path.join(local,'private-normalized');await mkdir(directory,{recursive:true,mode:0o700});await writeFile(path.join(directory,'snapshot.private.json'),JSON.stringify(snapshot),{mode:0o600});console.log(JSON.stringify({mode:'offline normalize only; no database writes',synthetic:snapshot.synthetic,counts:checked.counts,photoCount:files.length,output:'.local/private-normalized/snapshot.private.json',warning:'Sensitive private snapshot: encrypted backup required; never upload to Git or public trial'}));
}catch(e){console.error(/^([A-Z_]+)$/.test(e.message)?e.message:'SOURCE_REVIEW_FAILED');process.exitCode=1;}
