import {AppError,type Env} from './types';
import {session,login,digest} from './auth';
import {READS,read} from './reads';
import {write,changePin} from './writes';
import {upload,photo,cleanup} from './photos';
import {boundedBody} from './body';
import {nightly,dispatch} from './push';
import {unexpectedCategory} from './errors';
const messages:Record<string,string>={E_AUTH:'이름과 PIN을 확인하거나 다시 로그인해 주세요.',E_RATE:'로그인 시도가 많아요. 15분 뒤 다시 시도해 주세요.',E_FORBIDDEN:'접근 권한이 없어요.',E_NOT_FOUND:'자료를 찾을 수 없어요.',E_CONFLICT:'다른 기기에서 변경했거나 요청 내용이 달라졌어요. 작성 내용을 보관하고 새로 조회해 주세요.',E_INPUT:'입력 내용을 확인해 주세요.',E_VISIBILITY:'공개 범위를 확인해 주세요.',E_FILE_SIZE:'사진 크기는 1MB 이하여야 해요.',E_UPLOAD_EXPIRED:'첨부 보관 기간이 지났어요. 해당 사진을 다시 첨부해 주세요.',E_FILE_TYPE:'JPEG 또는 PNG 사진을 선택해 주세요.',E_PIN:'현재 PIN을 확인해 주세요.',E_PUSH_DISABLED:'시험 환경에서는 실제 알림 발송을 차단해요.',E_VERSION:'화면을 새로 열고 다시 시도해 주세요.'};
const json=(v:any,status=200)=>new Response(JSON.stringify(v),{status,headers:{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'}});
export default {async fetch(req:Request,env:Env,ctx:ExecutionContext){const url=new URL(req.url);if(!url.pathname.startsWith('/api/'))return env.ASSETS?.fetch(req)||new Response('Not found',{status:404});const origin=req.headers.get('Origin'),allowed=[...env.WEB_ORIGINS.split(',').map(x=>x.trim()),url.origin];let response:Response;
 try{if(origin&&!allowed.includes(origin))throw new AppError('E_ORIGIN',403);if(req.method==='OPTIONS'){if(!origin)throw new AppError('E_ORIGIN',403);response=new Response(null,{status:204});}else if(url.pathname==='/api/health'&&req.method==='GET'){response=json({ok:true,runtime:'Cloudflare Workers',storage:'D1 + private R2',push:env.PUSH_MODE,version:'cf-20261002'});}else{const token=req.headers.get('Authorization')?.replace(/^Bearer /,'')||'';
 if(req.method==='POST'&&(!origin||!allowed.includes(origin)))throw new AppError('E_ORIGIN',403);
 if(url.pathname==='/api/rpc'&&req.method==='POST'){if(req.headers.get('X-OKGU-Request')!=='1')throw new AppError('E_VERSION',409);const raw=new TextDecoder().decode(await boundedBody(req,32768,'E_INPUT'));let body:any;try{body=JSON.parse(raw);}catch{throw new AppError('E_INPUT');}if(!body||typeof body.method!=='string'||!Array.isArray(body.args)||body.args.length>15)throw new AppError('E_INPUT');if(body.method==='login')response=json(await login(env,...body.args.slice(0,3) as [any,any,any]));else {const a=await session(env,token);if(body.method==='logout'){await env.DB.prepare('DELETE FROM sessions WHERE token_hash=?').bind(await digest(token)).run();response=json({success:true});}else if(body.method==='changePin')response=json(await changePin(env,a,token,body.args));else if(READS.has(body.method))response=json(await read(env,a,body.method,body.args,body));else {response=json(await write({...env,APP_URL:new URL(env.APP_URL||'/okgu-diary-alarm-/',url.origin).href},a,token,body));ctx.waitUntil(dispatch(env,fetch,new Date(),3));}}}
 else if(url.pathname==='/api/photos'&&req.method==='POST')response=json(await upload(env,await session(env,token),req));else if(url.pathname.startsWith('/api/photos/')&&req.method==='GET')response=await photo(env,await session(env,token),url.pathname.slice(12),url.searchParams.get('thumb')==='1');else throw new AppError('E_METHOD',404);
 }}catch(error){const e=error instanceof AppError?error:new AppError('E_SERVER',500),category=unexpectedCategory(error);if(!(error instanceof AppError))console.error('worker_failure','E_SERVER',category);response=json({success:false,code:e.code,msg:messages[e.code]||'저장하지 못했어요. 작성 내용을 보관하고 다시 시도해 주세요.',...(env.TEST_MODE==='synthetic-trial'&&e.code==='E_SERVER'?{diagnostic:category}:{})},e.status);}
 const headers=new Headers(response.headers);if(origin&&allowed.includes(origin)){headers.set('Access-Control-Allow-Origin',origin);headers.set('Vary','Origin');headers.set('Access-Control-Allow-Methods','GET, POST, OPTIONS');headers.set('Access-Control-Allow-Headers','Authorization, Content-Type, X-OKGU-Request, X-Request-Id');headers.set('Access-Control-Max-Age','600');}headers.set('X-Content-Type-Options','nosniff');return new Response(response.body,{status:response.status,headers});},async scheduled(event:ScheduledController,env:Env,ctx:ExecutionContext){ctx.waitUntil((async()=>{if(event.cron==='0 4 * * *'){await cleanup(env);return;}if(event.cron==='0 13 * * *')await nightly(env,new Date(event.scheduledTime));await dispatch(env);})());}} satisfies ExportedHandler<Env>;
