import type {Env,Row} from './types';
import {today,all} from './store';
import {digest} from './auth';
export async function nightly(env:Env,at=new Date()){const date=today(at),now=at.getTime();const candidates=await all(env,"SELECT a.id FROM accounts a WHERE a.active=1 AND a.role='student' AND EXISTS(SELECT 1 FROM push_subscriptions s WHERE s.account_id=a.id AND s.enabled=1) AND NOT EXISTS(SELECT 1 FROM diaries d WHERE d.author_id=a.id AND d.diary_date=? AND d.deleted_at IS NULL)",[date]);for(const a of candidates){const key='nightly:'+date+':'+a.id;await env.DB.prepare('INSERT INTO push_jobs(id,event_key,account_id,payload,status,created_at,updated_at) VALUES(?,?,?,?,?,?,?) ON CONFLICT(event_key) DO NOTHING').bind(crypto.randomUUID(),key,a.id,JSON.stringify({title:'옥구 다이어리',body:'오늘의 하루를 기록해 볼까요?',url:env.APP_URL,tag:'okgu-nightly-'+date}),'pending',now,now).run();}return candidates.length;}
export async function dispatch(env:Env,transport:typeof fetch=fetch){if(env.PUSH_MODE!=='live'||env.ALLOW_LIVE_PUSH!=='approved'||!env.PUSH_SERVER_SECRET||!env.PUSH_SERVER_URL)return {blocked:true,sent:0};const jobs=await all(env,"SELECT * FROM push_jobs WHERE status='pending' ORDER BY created_at LIMIT 20");let sent=0;for(const job of jobs){if(job.event_key.startsWith('nightly:')){const day=job.event_key.split(':')[1];if(day!==today()||await env.DB.prepare('SELECT 1 FROM diaries WHERE author_id=? AND diary_date=? AND deleted_at IS NULL LIMIT 1').bind(job.account_id,day).first()){await env.DB.prepare("UPDATE push_jobs SET status='cancelled',updated_at=? WHERE id=? AND status='pending'").bind(Date.now(),job.id).run();continue;}}
 const subs=await all(env,'SELECT * FROM push_subscriptions WHERE account_id=? AND enabled=1',[job.account_id]);if(!subs.length)continue;const claim=await env.DB.prepare("UPDATE push_jobs SET status='dispatching',attempts=attempts+1,updated_at=? WHERE id=? AND status='pending'").bind(Date.now(),job.id).run();if(!claim.meta.changes)continue;
 // Existing push server has no idempotency key. A timeout is unknown, never automatically resent.
 try{const response=await transport(env.PUSH_SERVER_URL,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+env.PUSH_SERVER_SECRET},body:JSON.stringify({...JSON.parse(job.payload),subscriptions:subs.map(s=>JSON.parse(s.subscription))}),signal:AbortSignal.timeout(10000)});const result:any=await response.json();if(!response.ok||!result.ok)throw new Error('transport');for(const endpoint of result.expired||[]){const key=await digest(endpoint);await env.DB.prepare('UPDATE push_subscriptions SET enabled=0 WHERE endpoint_hash=? AND account_id=?').bind(key,job.account_id).run();}await env.DB.prepare("UPDATE push_jobs SET status='sent',updated_at=? WHERE id=?").bind(Date.now(),job.id).run();sent++;}catch{await env.DB.prepare("UPDATE push_jobs SET status='unknown',updated_at=? WHERE id=?").bind(Date.now(),job.id).run();}}
 return {blocked:false,sent};}
