import type {Env,Account,Row} from './types';
import {AppError} from './types';
import {pub} from './auth';
import {all,one,teacher,target,diary,post,list,decorate,diaryACL,boardACL,since,today,text} from './store';
export const READS=new Set(['verifyToken','getStudents','getMyEntries','getStudentDashboard','getBoard','getPraise','getRecentEntries','getClassOverview','getClassMoodStats','getStudentEntries','getNotifications','listAllPraiseForTeacher','listStudentFlags','getMoodTrend','exportMoodStatsCsv','getMyPushStatus','getPushSubscriptionStatus','getTeacherDashboardBundle','searchEntries','getMyStats','getEntry','exportEntries']);
export async function stats(env:Env,a:Account,period:string,author=a.id):Promise<Row>{const acl=diaryACL(a);const row=await one(env,`WITH visible AS(SELECT d.diary_date,d.mood_emoji FROM diaries d WHERE ${acl.sql} AND author_id=?), dates AS(SELECT DISTINCT diary_date FROM visible), ranked AS(SELECT diary_date,row_number() OVER(ORDER BY diary_date DESC) AS n FROM dates WHERE diary_date<=?),counts AS(SELECT mood_emoji,count(*) AS n FROM visible WHERE diary_date>=? GROUP BY mood_emoji) SELECT (SELECT json_group_object(mood_emoji,n) FROM counts) AS counts,(SELECT count(*) FROM visible WHERE diary_date>=?) AS total,(SELECT count(*) FROM dates) AS totalDays,(SELECT count(*) FROM ranked WHERE diary_date=date(?,printf('-%d days',n-1))) AS streak,(SELECT json_group_array(diary_date) FROM(SELECT diary_date FROM dates ORDER BY diary_date DESC LIMIT 7)) AS days`,[...acl.params,author,today(),since(period),since(period),today()]);return {...row,counts:JSON.parse(row.counts||'{}'),days:JSON.parse(row.days||'[]')};}
export async function overview(env:Env,a:Account){teacher(a);const acl=diaryACL(a);const rows=await all(env,`SELECT p.id,p.display_name,count(d.id) AS totalDays,max(CASE WHEN d.diary_date=? THEN 1 ELSE 0 END) AS wroteToday,(SELECT x.mood_emoji FROM diaries x WHERE x.author_id=p.id AND x.deleted_at IS NULL AND x.visibility<>'private' ORDER BY x.diary_date DESC,x.id DESC LIMIT 1) AS lastMood,max(d.diary_date) AS lastDate FROM accounts p LEFT JOIN diaries d ON d.author_id=p.id AND ${acl.sql} WHERE p.class_id=? AND p.role='student' AND p.active=1 GROUP BY p.id ORDER BY p.display_name`,[today(),...acl.params,a.class_id]);return rows.map(r=>({id:r.id,name:r.display_name,wroteToday:!!r.wroteToday,totalDays:r.totalDays,lastMood:r.lastMood||'',lastDate:r.lastDate||'',streak:0}));}
export async function classStats(env:Env,a:Account,period:string){teacher(a);const acl=diaryACL(a);const rows=await all(env,`SELECT mood_emoji,count(*) AS n FROM diaries d WHERE ${acl.sql} AND diary_date>=? GROUP BY mood_emoji`,[...acl.params,since(period)]);return {counts:Object.fromEntries(rows.map(r=>[r.mood_emoji,r.n])),total:rows.reduce((s,r)=>s+r.n,0)};}
async function trend(env:Env,a:Account,period:string){teacher(a);const acl=diaryACL(a);return {success:true,points:await all(env,`SELECT diary_date AS date,round(avg(CASE mood_emoji WHEN '😄' THEN 5 WHEN '🙂' THEN 4 WHEN '😐' THEN 3 WHEN '😢' THEN 2 ELSE 1 END),2) AS avg,count(*) AS count FROM diaries d WHERE ${acl.sql} AND diary_date>=? GROUP BY diary_date ORDER BY diary_date`,[...acl.params,since(period)])};}
async function flags(env:Env,a:Account){teacher(a);const rows=await all(env,'SELECT n.*,p.display_name,s.display_name AS setter FROM teacher_notes n JOIN accounts p ON p.id=n.student_id JOIN accounts s ON s.id=n.setter_id WHERE p.class_id=?',[a.class_id]);return {success:true,flags:Object.fromEntries(rows.map(r=>[r.display_name,{counsel:!!r.needs_counsel,memo:r.memo,by:r.setter,at:new Date(r.set_at).toISOString()}]))};}
async function praise(env:Env,a:Account,manage=false){if(manage)teacher(a);const rows=await all(env,`SELECT p.*,s.display_name AS sender,r.display_name AS recipient FROM praises p JOIN accounts s ON s.id=p.sender_id JOIN accounts r ON r.id=p.recipient_id WHERE p.deleted_at IS NULL AND s.class_id=? AND (p.sender_id=? OR (p.recipient_id=? AND p.approval='approved' AND p.hidden=0) OR ?=1) ORDER BY p.created_at DESC LIMIT 500`,[a.class_id,a.id,a.id,manage?1:0]);const convert=(p:Row,sent=false)=>({id:p.id,from:!manage&&!sent&&p.anonymous?'익명':p.sender,to:p.recipient,msg:p.body,anonymous:!!p.anonymous,hidden:!!p.hidden,status:p.approval,read:!!p.is_read,time:new Date(p.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}),timeISO:new Date(p.created_at).toISOString()});return manage?{success:true,items:rows.map(r=>convert(r))}:{received:rows.filter(r=>r.recipient_id===a.id).map(r=>convert(r)),sent:rows.filter(r=>r.sender_id===a.id).map(r=>convert(r,true))};}
async function pushFlags(env:Env,a:Account){teacher(a);const rows=await all(env,"SELECT a.display_name AS name,EXISTS(SELECT 1 FROM push_subscriptions p WHERE p.account_id=a.id AND p.enabled=1) AS enabled FROM accounts a WHERE a.class_id=? AND a.role='student' AND active=1",[a.class_id]);const items=rows.map(r=>({...r,enabled:!!r.enabled}));return {success:true,items,total:items.length,enabled:items.filter(r=>r.enabled).length};}
async function board(env:Env,a:Account,args:any[]){const [filter,,limit=12,offset=0]=args,acl=boardACL(a),size=Math.min(49,Math.max(1,Number(limit)||12));const rows=await all(env,`SELECT b.*,p.display_name FROM board_posts b JOIN accounts p ON p.id=b.author_id WHERE ${acl.sql} AND (?=0 OR b.author_id=?) ORDER BY b.created_at DESC,b.id DESC LIMIT ? OFFSET ?`,[...acl.params,filter==='mine'?1:0,a.id,size+1,Math.max(0,Number(offset)||0)]);const page=rows.slice(0,size);if(!page.length)return {posts:[],hasMore:false};const ids=page.map(r=>r.id),slots=ids.map(()=>'?').join(',');const [cs,ls,ps]=await env.DB.batch([env.DB.prepare(`SELECT c.*,a.display_name FROM board_comments c JOIN accounts a ON a.id=c.author_id WHERE c.post_id IN(${slots}) AND c.deleted_at IS NULL ORDER BY c.created_at,c.id`).bind(...ids),env.DB.prepare(`SELECT * FROM board_likes WHERE post_id IN(${slots})`).bind(...ids),env.DB.prepare(`SELECT f.*,b.id AS post_id FROM attachments f JOIN board_posts b ON b.diary_id=f.diary_id WHERE b.id IN(${slots}) ORDER BY f.ordinal`).bind(...ids)]);const comments=cs.results as Row[],likes=ls.results as Row[],photos=ps.results as Row[];return {posts:page.map(b=>({id:b.id,legacyId:b.legacy_id,author:b.display_name,text:b.body,mood:b.mood,date:b.date_label,timeHM:new Date(b.created_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}),likes:likes.filter(l=>l.post_id===b.id).length,liked:likes.some(l=>l.post_id===b.id&&l.account_id===a.id),photos:photos.filter(p=>p.post_id===b.id).map(p=>'okgu-photo:'+p.id),comments:comments.filter(c=>c.post_id===b.id).map(c=>({id:c.id,author:c.display_name,text:c.body,parentId:c.parent_id||'',time:new Date(c.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}),timeHM:new Date(c.created_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false})}))})),hasMore:rows.length>size};}
export async function read(env:Env,a:Account,method:string,args:any[],options:any):Promise<any>{switch(method){
case 'verifyToken':return pub(a);
case 'getStudents':return (await all(env,'SELECT display_name FROM accounts WHERE class_id=? AND active=1 ORDER BY role DESC,display_name',[a.class_id])).map(r=>r.display_name);
case 'getEntry':{const d=await diary(env,a,args[0]);const name=await one(env,'SELECT display_name FROM accounts WHERE id=?',[d.author_id]);return (await decorate(env,a,[{...d,...name}]))[0];}
case 'getMyEntries':return list(env,a,a.id,since('month'),50,options.offset||0);
case 'getStudentDashboard':{const period=options.period||'month',start=[since('month'),since(period==='all'?'month':period)].sort()[0];const entries=await list(env,a,a.id,start,50,options.offset||0);return {entries,nextOffset:entries.length===50?(options.offset||0)+50:null,teacherCommentMap:Object.fromEntries(entries.map(e=>[e.id,e.teacherComments])),stats:await stats(env,a,period),allStats:period==='all'?await stats(env,a,'all'):await stats(env,a,'all')};}
case 'getMyStats':return stats(env,a,args[0]||'all');
case 'searchEntries':{const q=text(args[0],100),acl=diaryACL(a),count=await one(env,`SELECT count(*) AS n FROM diaries d WHERE ${acl.sql} AND d.author_id=? AND (instr(d.body,?)>0 OR instr(d.mood_label,?)>0 OR instr(d.diary_date,?)>0)`,[...acl.params,a.id,q,q,q]);const entries=await list(env,a,a.id,'0001-01-01',50,options.offset||0,q);return {entries,total:count.n,hasMore:(options.offset||0)+entries.length<count.n};}
case 'exportEntries':{const owner=args[0]?await target(env,a,args[0]):a;if(owner.id!==a.id)teacher(a);return {entries:await list(env,a,owner.id,'0001-01-01',50,options.offset||0)};}
case 'getStudentEntries':{teacher(a);const s=await target(env,a,args[1]);return list(env,a,s.id,'0001-01-01',50,options.offset||0);}
case 'getRecentEntries':teacher(a);return list(env,a,undefined,'0001-01-01',Math.min(50,Number(args[1])||13),Number(args[2])||0);
case 'getBoard':return board(env,a,args);
case 'getPraise':return praise(env,a);
case 'listAllPraiseForTeacher':return praise(env,a,true);
case 'getClassOverview':{const rows=await overview(env,a);for(const r of rows)r.streak=(await stats(env,a,'all',r.id)).streak;return rows;}
case 'getClassMoodStats':return classStats(env,a,args[1]||'week');
case 'getMoodTrend':return trend(env,a,args[1]||'week');
case 'listStudentFlags':return flags(env,a);
case 'getMyPushStatus':return {success:true,enabled:!!await env.DB.prepare('SELECT 1 FROM push_subscriptions WHERE account_id=? AND enabled=1 LIMIT 1').bind(a.id).first()};
case 'getPushSubscriptionStatus':return pushFlags(env,a);
case 'getTeacherDashboardBundle':{teacher(a);const rows=await overview(env,a);for(const r of rows)r.streak=(await stats(env,a,'all',r.id)).streak;return {overview:rows,flags:(await flags(env,a)).flags,mood:await classStats(env,a,args[0]||'today'),trend:(await trend(env,a,args[1]||'week')).points,praise:(await praise(env,a,true)).items,push:await pushFlags(env,a)};}
case 'exportMoodStatsCsv':{teacher(a);const acl=diaryACL(a),rows=await all(env,`SELECT d.diary_date,a.display_name,d.mood_label FROM diaries d JOIN accounts a ON a.id=d.author_id WHERE ${acl.sql} AND d.diary_date>=? ORDER BY d.diary_date,a.display_name`,[...acl.params,since(args[1]||'week')]);const cell=(s:string)=>'"'+(/^[=+\-@\t\r]/.test(s)?"'":'')+s.replace(/"/g,'""')+'"';return {success:true,csv:'\ufeff날짜,학생,기분\r\n'+rows.map(r=>[r.diary_date,r.display_name,r.mood_label].map(cell).join(',')).join('\r\n'),filename:'옥구_기분_'+today()+'.csv'};}
case 'getNotifications':{const rows=await all(env,'SELECT n.*,a.display_name FROM notifications n JOIN accounts a ON a.id=n.actor_id WHERE n.recipient_id=? AND n.created_at>? ORDER BY n.created_at DESC LIMIT 100',[a.id,Date.now()-7*86400000]);const visible=[];for(const n of rows){try{if(['diary','comment','reply'].includes(n.type))await diary(env,a,n.link_id);if(n.type==='board')await post(env,a,n.link_id);if(n.type==='praise')await one(env,"SELECT id FROM praises WHERE id=? AND recipient_id=? AND approval='approved' AND hidden=0 AND deleted_at IS NULL",[n.link_id,a.id]);}catch{continue;}visible.push({type:n.type==='diary'?'comment':n.type,id:n.id,diaryId:n.link_id,postId:n.link_id,from:n.display_name,text:'새 소식이 있어요.',timeISO:new Date(n.created_at).toISOString(),time:new Date(n.created_at).toLocaleDateString('ko-KR',{timeZone:'Asia/Seoul'}),commentId:n.comment_id});}return {success:true,items:visible,notifications:visible};}
default:throw new AppError('E_METHOD',404);
}}
