import {AppError,type Account,type Env,type Row} from './types';
export const all=async(env:Env,sql:string,p:any[]=[])=>((await env.DB.prepare(sql).bind(...p).all<Row>()).results||[]);
export const one=async(env:Env,sql:string,p:any[]=[])=>{const r=await env.DB.prepare(sql).bind(...p).first<Row>();if(!r)throw new AppError('E_NOT_FOUND',404);return r;};
export const teacher=(a:Account)=>{if(a.role!=='teacher')throw new AppError('E_FORBIDDEN',403);};
export const today=(date=new Date())=>date.toLocaleDateString('en-CA',{timeZone:'Asia/Seoul'});
export const text=(v:unknown,max=2000)=>{if(typeof v!=='string'||!v.trim()||[...v].length>max)throw new AppError('E_INPUT');return v;};
export function since(period:string){const day=today();if(period==='today')return day;if(period==='month')return day.slice(0,8)+'01';if(period==='week'){const d=new Date(day+'T00:00:00Z');d.setUTCDate(d.getUTCDate()-((d.getUTCDay()||7)-1));return d.toISOString().slice(0,10);}return '0001-01-01';}
export const diaryACL=(a:Account,alias='d')=>({sql:`${alias}.deleted_at IS NULL AND (${alias}.author_id=? OR (${alias}.class_id=? AND (${alias}.visibility='class' OR (${alias}.visibility='teacher' AND ?='teacher'))))`,params:[a.id,a.class_id,a.role]});
export async function diary(env:Env,a:Account,id:unknown){const acl=diaryACL(a);return one(env,`SELECT d.* FROM diaries d WHERE (d.id=? OR d.legacy_id=?) AND ${acl.sql}`,[String(id),String(id),...acl.params]);}
export const boardACL=(a:Account,alias='b')=>({sql:`${alias}.deleted_at IS NULL AND EXISTS(SELECT 1 FROM accounts peer WHERE peer.id=${alias}.author_id AND peer.class_id=?) AND (${alias}.diary_id IS NULL OR EXISTS(SELECT 1 FROM diaries d WHERE d.id=${alias}.diary_id AND d.deleted_at IS NULL AND d.visibility='class'))`,params:[a.class_id]});
export async function post(env:Env,a:Account,id:unknown){const acl=boardACL(a);return one(env,`SELECT b.* FROM board_posts b WHERE (b.id=? OR b.legacy_id=?) AND ${acl.sql}`,[String(id),String(id),...acl.params]);}
export async function target(env:Env,a:Account,name:unknown){const rows=await all(env,'SELECT * FROM accounts WHERE display_name=? AND class_id=? AND active=1',[String(name),a.class_id]);if(rows.length!==1)throw new AppError('E_INPUT');return rows[0];}
export const teachers=async(env:Env,a:Account)=>(await all(env,"SELECT id FROM accounts WHERE class_id=? AND role='teacher' AND active=1",[a.class_id])).map(r=>r.id);
export function relativeTime(t:number,now=Date.now()){if(!Number.isFinite(t))return '';const seconds=Math.floor((now-t)/1000);if(seconds<60)return '방금';if(seconds<3600)return Math.floor(seconds/60)+'분 전';if(seconds<86400)return Math.floor(seconds/3600)+'시간 전';if(seconds<172800)return '어제';const d=new Date(t+9*3600000);return (d.getUTCMonth()+1)+'월 '+d.getUTCDate()+'일';}
export function savedTime(t:number){if(!Number.isFinite(t))return '';const d=new Date(t+9*3600000),hour=d.getUTCHours();return (d.getUTCMonth()+1)+'월 '+d.getUTCDate()+'일 '+(hour<12?'오전':'오후')+' '+(hour%12||12)+':'+String(d.getUTCMinutes()).padStart(2,'0');}
export function entry(r:Row){return {id:r.id,legacyId:r.legacy_id||null,date:r.diary_date,studentName:r.display_name,text:r.body,moodEmoji:r.mood_emoji,moodLabel:r.mood_label,moodColor:r.mood_color,isSecret:!!r.legacy_secret,isPublic:r.visibility==='class',isMeOnly:r.visibility==='private',version:r.version,timestamp:r.updated_at,savedAt:relativeTime(r.updated_at),savedTime:savedTime(r.updated_at),timeHM:new Date(r.updated_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false}),photos:r.photos||[],teacherComments:r.teacherComments||[],boardComments:r.boardComments||[]};}
export async function decorate(env:Env,a:Account,rows:Row[]){if(!rows.length)return [];const ids=rows.map(r=>r.id),slots=ids.map(()=>'?').join(',');
 const results=await env.DB.batch([env.DB.prepare(`SELECT * FROM attachments WHERE diary_id IN(${slots}) ORDER BY ordinal`).bind(...ids),env.DB.prepare(`SELECT c.*,p.display_name,p.role FROM diary_comments c JOIN accounts p ON p.id=c.author_id WHERE c.diary_id IN(${slots}) AND c.deleted_at IS NULL ORDER BY c.created_at,c.id`).bind(...ids),env.DB.prepare(`SELECT c.*,p.display_name,b.diary_id FROM board_comments c JOIN board_posts b ON b.id=c.post_id JOIN accounts p ON p.id=c.author_id WHERE b.diary_id IN(${slots}) AND b.deleted_at IS NULL AND c.deleted_at IS NULL AND EXISTS(SELECT 1 FROM diaries d WHERE d.id=b.diary_id AND d.visibility='class' AND d.deleted_at IS NULL) ORDER BY c.created_at,c.id`).bind(...ids)]);
 const [photos,comments,board]=results.map(r=>r.results as Row[]);const comment=(c:Row)=>({id:c.id,author:c.display_name,teacher:c.display_name,text:c.body,parentId:c.parent_id||'',role:c.role==='teacher'?'선생님':'학생',time:relativeTime(c.created_at),timestamp:c.created_at,timeISO:new Date(c.created_at).toISOString(),timeHM:new Date(c.created_at).toLocaleTimeString('ko-KR',{timeZone:'Asia/Seoul',hour:'2-digit',minute:'2-digit',hour12:false})});
 return rows.map(r=>entry({...r,photos:photos.filter(f=>f.diary_id===r.id).map(f=>'okgu-photo:'+f.id),teacherComments:comments.filter(c=>c.diary_id===r.id).map(comment),boardComments:board.filter(c=>c.diary_id===r.id).map(comment)}));
}
export async function list(env:Env,a:Account,author:string|undefined,start='0001-01-01',limit=50,offset=0,query='',order:'saved'|'created'='saved'){
 const acl=diaryACL(a),ordering=order==='created'?'d.created_at DESC,d.id DESC':'d.updated_at DESC,d.id DESC';const rows=await all(env,`SELECT d.*,p.display_name FROM diaries d JOIN accounts p ON p.id=d.author_id WHERE ${acl.sql} AND (? IS NULL OR d.author_id=?) AND d.diary_date>=? AND (instr(d.body,?)>0 OR instr(d.mood_label,?)>0 OR instr(d.diary_date,?)>0) ORDER BY ${ordering} LIMIT ? OFFSET ?`,[...acl.params,author||null,author||null,start,query,query,query,Math.min(50,Math.max(1,limit)),Math.max(0,offset)]);
 return decorate(env,a,rows);
}
