import {AppError,type Env,type Account,type Row} from './types';
import {digest,hashPin,verifyPin} from './auth';
import {all,one,target,teacher,diary,post,diaryACL,boardACL,teachers,text,entry} from './store';
const uuid=/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;
const moods:Record<string,string>={'😄':'신남','🙂':'좋아','😐':'그냥','😢':'슬퍼','😠':'화남'};
export async function changePin(env:Env,a:Account,token:string,args:any[]){const old=await one(env,'SELECT pin_hash FROM credentials WHERE account_id=?',[a.id]);if(!await verifyPin(text(args[1],20),old.pin_hash))throw new AppError('E_PIN',403);const pin=text(args[2],20);if(pin.length<4)throw new AppError('E_INPUT');const hash=await hashPin(pin),tokenHash=await digest(token);const result=await env.DB.batch([env.DB.prepare('UPDATE credentials SET pin_hash=? WHERE account_id=? AND pin_hash=? AND EXISTS(SELECT 1 FROM sessions s JOIN accounts a ON a.id=s.account_id WHERE s.token_hash=? AND s.expires_at>? AND a.active=1 AND a.id=?)').bind(hash,a.id,old.pin_hash,tokenHash,Date.now(),a.id),env.DB.prepare('DELETE FROM sessions WHERE account_id=? AND token_hash<>? AND EXISTS(SELECT 1 FROM credentials WHERE account_id=? AND pin_hash=?)').bind(a.id,tokenHash,a.id,hash)]);if(result[0].meta.changes!==1)throw new AppError('E_CONFLICT',409);return {success:true};}
export async function write(env:Env,a:Account,token:string,body:any){const {method,args,requestId}=body;if(typeof requestId!=='string'||!uuid.test(requestId))throw new AppError('E_INPUT');const payloadHash=await digest(JSON.stringify({method,args,expectedVersion:body.expectedVersion}));const previous=await env.DB.prepare('SELECT * FROM receipts WHERE account_id=? AND request_id=?').bind(a.id,requestId).first<Row>();if(previous){if(previous.payload_hash!==payloadHash)throw new AppError('E_CONFLICT',409);return decode(previous.result);}
 const nonce=crypto.randomUUID(),now=Date.now(),hash=await digest(token),queries:D1PreparedStatement[]=[];
 const guard='EXISTS(SELECT 1 FROM receipts r JOIN accounts a ON a.id=r.account_id JOIN sessions s ON s.account_id=a.id WHERE r.account_id=? AND r.request_id=? AND r.nonce=? AND a.active=1 AND a.role=? AND a.class_id=? AND s.token_hash=? AND s.expires_at>?)';const gp=[a.id,requestId,nonce,a.role,a.class_id,hash,now];
 queries.push(env.DB.prepare("INSERT INTO receipts(account_id,request_id,payload_hash,nonce,result,created_at) VALUES(?,?,?,?,?,?) ON CONFLICT DO NOTHING").bind(a.id,requestId,payloadHash,nonce,'{}',now));
 const q=(sql:string,params:any[]=[])=>queries.push(env.DB.prepare(sql).bind(...params));
 let proof='1=1',proofParams:any[]=[],result:any={success:true},finalExpression='?',finalParams:any[]=[];
 const aclDiary=(id:string)=>{const acl=diaryACL(a);return {sql:`EXISTS(SELECT 1 FROM diaries d WHERE d.id=? AND ${acl.sql})`,p:[id,...acl.params]};};
 const aclPost=(id:string)=>{const acl=boardACL(a);return {sql:`EXISTS(SELECT 1 FROM board_posts b WHERE b.id=? AND ${acl.sql})`,p:[id,...acl.params]};};
 const root=(table:string,id:string)=>{proof=`EXISTS(SELECT 1 FROM ${table} WHERE id=? AND last_request_id=?)`;proofParams=[id,nonce];};
 const queue=(recipient:string,type:string,link:string,comment='')=>{
  const url=new URL(env.APP_URL);if(type!=='test'){url.searchParams.set('open',type==='board'?'board':type.startsWith('praise')?'praise':'diary');url.searchParams.set('id',link);if(comment)url.searchParams.set('cid',comment);}
  const payload={title:type==='test'?'OKGU DIARY 푸시 테스트':'OKGU DIARY',body:type==='test'?'푸시 알림 연결을 확인해 주세요.':'새 소식이 있어요.',url:url.href,tag:method+':'+requestId,guard:{type,link,comment}};
  q(`INSERT INTO push_jobs(id,event_key,account_id,payload,status,created_at,updated_at) SELECT ?,?,?,?,'pending',?,? WHERE ${guard} AND ${proof} ON CONFLICT(event_key) DO NOTHING`,[crypto.randomUUID(),method+':'+requestId+':'+recipient,recipient,JSON.stringify(payload),now,now,...gp,...proofParams]);
 };
 const notify=(recipients:string[],type:string,link:string,comment='')=>{for(const recipient of new Set(recipients))if(recipient!==a.id){
  q(`INSERT INTO notifications(id,recipient_id,actor_id,event_key,type,link_id,comment_id,created_at) SELECT ?,?,?,?,?,?,?,? WHERE ${guard} AND ${proof} ON CONFLICT(recipient_id,event_key) DO NOTHING`,[crypto.randomUUID(),recipient,a.id,method+':'+requestId,type,link,comment,now,...gp,...proofParams]);
  queue(recipient,type,link,comment);
 }};
 switch(method){
 case 'saveEntry':{if(a.role!=='student')throw new AppError('E_FORBIDDEN',403);const [,date,emoji,label,color,bodyText,secret,pub,priv,photoJSON,oldId]=args;text(bodyText);if(typeof date!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(date)||!Number.isFinite(Date.parse(date))||new Date(date).toISOString().slice(0,10)!==date||moods[emoji]!==label||typeof color!=='string'||!/^#[\da-f]{3,8}$/i.test(color)||[secret,pub,priv].some(v=>typeof v!=='boolean'))throw new AppError('E_INPUT');if((secret||priv)&&pub)throw new AppError('E_VISIBILITY');let refs:any;try{refs=JSON.parse(photoJSON||'[]');}catch{throw new AppError('E_INPUT');}if(!Array.isArray(refs)||refs.length>4||new Set(refs).size!==refs.length||refs.some(r=>typeof r!=='string'||!uuid.test(r.slice(11))||!r.startsWith('okgu-photo:')))throw new AppError('E_INPUT');
 let old:Row|undefined;if(oldId){old=await diary(env,a,oldId);if(old.author_id!==a.id)throw new AppError('E_FORBIDDEN',403);if(!Number.isInteger(body.expectedVersion)||old.version!==body.expectedVersion)throw new AppError('E_CONFLICT',409);}
 const id=old?.id||crypto.randomUUID(),version=(old?.version||0)+1,visibility=priv?'private':pub?'class':'teacher',photos:Row[]=[];
 for(const ref of refs){const photoId=ref.slice(11);const existing=await env.DB.prepare('SELECT * FROM attachments WHERE id=? AND diary_id=?').bind(photoId,id).first<Row>();photos.push(existing||await one(env,'SELECT * FROM photo_uploads WHERE id=? AND owner_id=? AND ready=1 AND (diary_id IS NULL OR diary_id=?)',[photoId,a.id,id]));}
 // The ownership of every upload is rechecked inside the atomic D1 batch.
 const validPhotos=photos.map(()=>'(EXISTS(SELECT 1 FROM attachments WHERE id=? AND diary_id=?) OR EXISTS(SELECT 1 FROM photo_uploads WHERE id=? AND owner_id=? AND ready=1 AND (diary_id IS NULL OR diary_id=?)))').join(' AND ')||'1=1';const vp=photos.flatMap(p=>[p.id,id,p.id,a.id,id]);
 if(old)q(`UPDATE diaries SET diary_date=?,body=?,mood_emoji=?,mood_label=?,mood_color=?,visibility=?,legacy_secret=?,updated_at=?,version=version+1,last_request_id=? WHERE id=? AND author_id=? AND version=? AND deleted_at IS NULL AND ${guard} AND ${validPhotos}`,[date,bodyText,emoji,label,color,visibility,secret?1:0,now,nonce,id,a.id,body.expectedVersion,...gp,...vp]);
 else q(`INSERT INTO diaries(id,author_id,class_id,diary_date,body,mood_emoji,mood_label,mood_color,visibility,legacy_secret,created_at,updated_at,last_request_id) SELECT ?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${guard} AND ${validPhotos}`,[id,a.id,a.class_id,date,bodyText,emoji,label,color,visibility,secret?1:0,now,now,nonce,...gp,...vp]);root('diaries',id);
 q(`UPDATE photo_uploads SET diary_id=NULL,detached_at=? WHERE diary_id=? AND id NOT IN(${photos.map(()=>'?').join(',')||"''"}) AND ${guard} AND ${proof}`,[now,id,...photos.map(p=>p.id),...gp,...proofParams]);
 q(`DELETE FROM attachments WHERE diary_id=? AND ${guard} AND ${proof}`,[id,...gp,...proofParams]);
 for(const [ordinal,p] of photos.entries()){q(`UPDATE photo_uploads SET diary_id=?,detached_at=NULL WHERE id=? AND owner_id=? AND ${guard} AND ${proof}`,[id,p.id,a.id,...gp,...proofParams]);q(`INSERT INTO attachments(id,diary_id,object_path,ordinal,sha256,byte_size,mime_type,legacy_file_id,thumbnail_path) SELECT ?,?,?,?,?,?,?,?,? WHERE ${guard} AND ${proof}`,[p.id,id,p.object_path,ordinal,p.sha256,p.byte_size,p.mime_type,p.legacy_file_id||null,p.thumbnail_path||null,...gp,...proofParams]);}
 q(`UPDATE board_posts SET deleted_at=?,last_request_id=? WHERE diary_id=? AND ${guard} AND ${proof}`,[now,nonce,id,...gp,...proofParams]);if(visibility==='class')q(`INSERT INTO board_posts(id,diary_id,author_id,body,mood,date_label,created_at,last_request_id) SELECT ?,?,?,?,?,?,?,? WHERE ${guard} AND ${proof} ON CONFLICT(diary_id) DO UPDATE SET body=excluded.body,mood=excluded.mood,date_label=excluded.date_label,deleted_at=NULL,last_request_id=excluded.last_request_id`,[id,id,a.id,bodyText,emoji,date,now,nonce,...gp,...proofParams]);
 if(visibility!=='private')notify(await teachers(env,a),'diary',id);
 result={success:true,id,version,entry:entry({id,diary_date:date,display_name:a.display_name,body:bodyText,mood_emoji:emoji,mood_label:label,mood_color:color,visibility,legacy_secret:secret,version,updated_at:now,photos:refs})};break;}
 case 'deleteEntry':case 'deleteEntryAsTeacher':{const d=await diary(env,a,args[1]);if(method==='deleteEntryAsTeacher')teacher(a);else if(d.author_id!==a.id)throw new AppError('E_FORBIDDEN',403);if(body.expectedVersion!==d.version)throw new AppError('E_CONFLICT',409);const access=aclDiary(d.id);q(`UPDATE diaries SET deleted_at=?,version=version+1,last_request_id=? WHERE id=? AND version=? AND ${guard} AND ${access.sql}`,[now,nonce,d.id,body.expectedVersion,...gp,...access.p]);root('diaries',d.id);q(`UPDATE board_posts SET deleted_at=? WHERE diary_id=? AND ${guard} AND ${proof}`,[now,d.id,...gp,...proofParams]);break;}
 case 'deleteBoard':{const b=await post(env,a,args[1]);if(b.author_id!==a.id)throw new AppError('E_FORBIDDEN',403);const access=aclPost(b.id);q(`UPDATE board_posts SET deleted_at=?,last_request_id=? WHERE id=? AND author_id=? AND ${guard} AND ${access.sql}`,[now,nonce,b.id,a.id,...gp,...access.p]);root('board_posts',b.id);break;}
 case 'toggleLike':{const b=await post(env,a,args[0]),access=aclPost(b.id);q(`UPDATE receipts SET result=json_object('wasLiked',EXISTS(SELECT 1 FROM board_likes WHERE post_id=? AND account_id=?)) WHERE account_id=? AND request_id=? AND nonce=? AND ${guard} AND ${access.sql}`,[b.id,a.id,a.id,requestId,nonce,...gp,...access.p]);const was=`(SELECT json_extract(result,'$.wasLiked') FROM receipts WHERE account_id=? AND request_id=? AND nonce=?)`,wp=[a.id,requestId,nonce];q(`DELETE FROM board_likes WHERE post_id=? AND account_id=? AND ${guard} AND ${access.sql} AND ${was}=1`,[b.id,a.id,...gp,...access.p,...wp]);q(`INSERT INTO board_likes(post_id,account_id,last_request_id) SELECT ?,?,? WHERE ${guard} AND ${access.sql} AND ${was}=0 ON CONFLICT DO NOTHING`,[b.id,a.id,nonce,...gp,...access.p,...wp]);proof=access.sql;proofParams=access.p;finalExpression=`json_object('success',json('true'),'liked',json(CASE WHEN json_extract(result,'$.wasLiked')=0 THEN 'true' ELSE 'false' END),'likes',(SELECT count(*) FROM board_likes WHERE post_id=?))`;finalParams=[b.id];break;}
 case 'addComment':case 'addTeacherComment':case 'addStudentReplyToDiary':{const board=method==='addComment',dest=board?await post(env,a,args[0]):await diary(env,a,method==='addTeacherComment'?args[1]:args[0]);if(method==='addTeacherComment')teacher(a);if(method==='addStudentReplyToDiary'&&dest.author_id!==a.id)throw new AppError('E_FORBIDDEN',403);const table=board?'board_comments':'diary_comments',field=board?'post_id':'diary_id',access=board?aclPost(dest.id):aclDiary(dest.id),content=text(args[2],method==='addTeacherComment'?1000:500);let parent=args[3]||'',parentAuthor='';if(parent){const p=await one(env,`SELECT * FROM ${table} WHERE (id=? OR legacy_id=?) AND deleted_at IS NULL`,[parent,parent]);if(p[field]!==dest.id)throw new AppError('E_INPUT');parent=p.id;parentAuthor=p.author_id;}const id=crypto.randomUUID();q(`INSERT INTO ${table}(id,${field},author_id,body,created_at,parent_id,last_request_id) SELECT ?,?,?,?,?,?,? WHERE ${guard} AND ${access.sql} AND (? IS NULL OR EXISTS(SELECT 1 FROM ${table} WHERE id=? AND ${field}=? AND deleted_at IS NULL))`,[id,dest.id,a.id,content,now,parent||null,nonce,...gp,...access.p,parent||null,parent||null,dest.id]);root(table,id);notify([dest.author_id,...(board?[]:await teachers(env,a)),...(parentAuthor?[parentAuthor]:[])],board?'board':a.role==='teacher'?'comment':'reply',dest.id,id);result={success:true,id,time:'방금',parentId:parent};break;}
 case 'editComment':case 'editTeacherComment':case 'deleteComment':case 'deleteTeacherComment':{const board=!method.includes('Teacher'),table=board?'board_comments':'diary_comments',field=board?'post_id':'diary_id';const c=await one(env,`SELECT * FROM ${table} WHERE (id=? OR legacy_id=?) AND deleted_at IS NULL`,[String(args[1]),String(args[1])]);if(c.author_id!==a.id)throw new AppError('E_FORBIDDEN',403);if(board)await post(env,a,c[field]);else await diary(env,a,c[field]);const access=board?aclPost(c[field]):aclDiary(c[field]);if(method.startsWith('delete'))q(`UPDATE ${table} SET deleted_at=?,last_request_id=? WHERE id=? AND author_id=? AND deleted_at IS NULL AND ${guard} AND ${access.sql}`,[now,nonce,c.id,a.id,...gp,...access.p]);else q(`UPDATE ${table} SET body=?,last_request_id=? WHERE id=? AND author_id=? AND deleted_at IS NULL AND ${guard} AND ${access.sql}`,[text(args[2],board?500:1000),nonce,c.id,a.id,...gp,...access.p]);root(table,c.id);if(method.startsWith('delete'))q(`UPDATE ${table} SET parent_id=NULL WHERE parent_id=? AND ${guard} AND ${proof}`,[c.id,...gp,...proofParams]);break;}
 case 'sendPraise':{
  const group=args[1]==='담임',recipient=group?'homeroom:'+a.class_id:(await target(env,a,args[1])).id,id=crypto.randomUUID();
  if(group)q(`INSERT INTO accounts(id,legacy_identity,display_name,class_id,role,active) SELECT ?,?,'담임',?,'teacher',0 WHERE ${guard} ON CONFLICT DO NOTHING`,[recipient,'system:'+recipient,a.class_id,...gp]);
  q(`INSERT INTO praises(id,sender_id,recipient_id,body,created_at,anonymous,approval,last_request_id) SELECT ?,?,?,?,?,?,'pending',? WHERE ${guard} AND EXISTS(SELECT 1 FROM accounts WHERE id=? AND (active=1 OR id=?) AND class_id=?)`,[id,a.id,recipient,text(args[2],300),now,args[3]===true?1:0,nonce,...gp,recipient,'homeroom:'+a.class_id,a.class_id]);root('praises',id);
  notify(await teachers(env,a),'praise-review',id);result={success:true,id};break;
 }
 case 'markPraiseRead':{
  const ids=args[0];if(!Array.isArray(ids)||ids.length>50||ids.some(id=>typeof id!=='string'||!uuid.test(id)))throw new AppError('E_INPUT');
  q(`UPDATE praises SET is_read=1 WHERE id IN(${ids.map(()=>'?').join(',')||"''"}) AND (recipient_id=? OR (?='teacher' AND recipient_id=?)) AND approval='approved' AND hidden=0 AND deleted_at IS NULL AND ${guard}`,[...ids,a.id,a.role,'homeroom:'+a.class_id,...gp]);break;
 }
 case 'setPraiseStatus':case 'setPraiseHidden':case 'deletePraiseAsTeacher':{teacher(a);const p=await one(env,'SELECT p.* FROM praises p JOIN accounts s ON s.id=p.sender_id JOIN accounts r ON r.id=p.recipient_id WHERE (p.id=? OR p.legacy_id=?) AND p.deleted_at IS NULL AND s.class_id=? AND r.class_id=?',[String(args[1]),String(args[1]),a.class_id,a.class_id]);let field='',value:any;if(method==='setPraiseStatus'){if(!['approved','pending','rejected'].includes(args[2]))throw new AppError('E_INPUT');field='approval';value=args[2];}else if(method==='setPraiseHidden'){if(typeof args[2]!=='boolean')throw new AppError('E_INPUT');field='hidden';value=args[2]?1:0;}else {field='deleted_at';value=now;}q(`UPDATE praises SET ${field}=?,last_request_id=? WHERE id=? AND deleted_at IS NULL AND ${guard}`,[value,nonce,p.id,...gp]);root('praises',p.id);if(field==='approval'&&value==='approved')notify(p.recipient_id==='homeroom:'+a.class_id?await teachers(env,a):[p.recipient_id],'praise',p.id);break;}
 case 'setStudentCounselFlag':{teacher(a);const s=await target(env,a,args[1]);if(s.role!=='student'||typeof args[2]!=='boolean'||String(args[3]||'').length>2000)throw new AppError('E_INPUT');q(`INSERT INTO teacher_notes(student_id,needs_counsel,memo,setter_id,set_at,last_request_id) SELECT ?,?,?,?,?,? WHERE ${guard} ON CONFLICT(student_id) DO UPDATE SET needs_counsel=excluded.needs_counsel,memo=excluded.memo,setter_id=excluded.setter_id,set_at=excluded.set_at,last_request_id=excluded.last_request_id`,[s.id,args[2]?1:0,String(args[3]||''),a.id,now,nonce,...gp]);proof='EXISTS(SELECT 1 FROM teacher_notes WHERE student_id=? AND last_request_id=?)';proofParams=[s.id,nonce];break;}
 case 'savePushSubscription':{let sub:any;try{sub=JSON.parse(args[3]);const u=new URL(sub.endpoint);if(u.protocol!=='https:'||!['fcm.googleapis.com','updates.push.services.mozilla.com','web.push.apple.com'].includes(u.hostname)||u.username||u.password||!sub.keys?.p256dh||!sub.keys?.auth||JSON.stringify(sub).length>4096)throw 0;}catch{throw new AppError('E_INPUT');}const key=await digest(sub.endpoint);const previous=await env.DB.prepare('SELECT account_id FROM push_subscriptions WHERE endpoint_hash=?').bind(key).first<Row>();if(previous&&previous.account_id!==a.id)throw new AppError('E_FORBIDDEN',403);q(`INSERT INTO push_subscriptions(endpoint_hash,account_id,subscription,updated_at,last_request_id) SELECT ?,?,?,?,? WHERE ${guard} ON CONFLICT(endpoint_hash) DO UPDATE SET subscription=excluded.subscription,enabled=1,updated_at=excluded.updated_at,last_request_id=excluded.last_request_id WHERE push_subscriptions.account_id=excluded.account_id`,[key,a.id,JSON.stringify(sub),now,nonce,...gp]);proof='EXISTS(SELECT 1 FROM push_subscriptions WHERE endpoint_hash=? AND account_id=? AND last_request_id=?)';proofParams=[key,a.id,nonce];break;}
 case 'disablePushSubscription':q(`UPDATE push_subscriptions SET enabled=0,last_request_id=? WHERE account_id=? AND ${guard}`,[requestId,a.id,...gp]);break;
 case 'sendTestPush':if(env.PUSH_MODE!=='live'||env.ALLOW_LIVE_PUSH!=='approved')throw new AppError('E_PUSH_DISABLED',503);queue(a.id,'test',a.id);result={success:true,queued:true,msg:'테스트 알림을 요청했어요. 기기에 도착하는지 확인해 주세요.'};break;
 default:throw new AppError('E_METHOD',404);
 }
 if(finalExpression==='?')finalParams=[JSON.stringify(result)];q(`UPDATE receipts SET result=CASE WHEN ${proof} AND ${guard} THEN ${finalExpression} ELSE '{"error":"E_CONFLICT"}' END WHERE account_id=? AND request_id=? AND nonce=?`,[...proofParams,...gp,...finalParams,a.id,requestId,nonce]);
 await env.DB.batch(queries);const receipt=await one(env,'SELECT * FROM receipts WHERE account_id=? AND request_id=?',[a.id,requestId]);if(receipt.payload_hash!==payloadHash)throw new AppError('E_CONFLICT',409);return decode(receipt.result);
}
function decode(value:string){const parsed=JSON.parse(value);if(parsed.error)throw new AppError(parsed.error,409);if(!parsed.success)throw new AppError('E_CONFLICT',409);return parsed;}
